### ISSUE TITLE
Rustup segfaults on POWER8

### ISSUE THREAD

**Issue by lu-zero** [rust-lang-deprecated/rustup.sh#68]
To reproduce:

```
curl https://sh.rustup.rs -sSf | sh
info: downloading installer
sh: line 250: 16025 Segmentation fault      (core dumped) "$@"
rustup: command failed: /tmp/tmp.0hp65M1orc/rustup-init
```

The system:

```
Linux rh-power-vm49 4.4.6-300.fc23.ppc64le #1 SMP Wed Mar 23 19:27:26 UTC 2016 ppc64le ppc64le ppc64le GNU/Linux
```

The actual version:

```
/tmp/tmp.XdYY5WgBxH/rustup-init -V
rustup-init 0.6.1 (71f7482 2016-08-24)
```

The backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000205f0c38 in je_huge_dalloc ()
Missing separate debuginfos, use: dnf debuginfo-install libgcc-5.3.1-6.fc23.ppc64le
(gdb) bt
#0  0x00000000205f0c38 in je_huge_dalloc ()
#1  0x00000000205cd7f0 in sdallocx ()
#2  0x00000000205c5e4c in __rust_deallocate ()
#3  0x00000000200e1300 in rustup_init::self_update::do_anti_sudo_check::home_mismatch::heb4fde5439976c13 ()
#4  0x00000000200dbfac in rustup_init::self_update::install::h5c8318effea204c9 ()
#5  0x00000000200f0fe8 in rustup_init::main::he9ea588d309e0baa ()
#6  0x00000000205b73a4 in std::panicking::try::do_call::h9d5ad283de22edbd ()
#7  0x00000000205c1f48 in __rust_maybe_catch_panic ()
#8  0x00000000205b6220 in std::rt::lang_start::h352a66f5026f54bd ()
#9  0x00000000200f2cf8 in main ()
```

**Comment by brson** [comment]
Thanks for the report! Tracking in https://github.com/rust-lang/rust/issues/36023. Going to close this in favor of that.

**Comment by brson** [comment]
Should be fixed.

**Comment by lu-zero** [comment]
Confirmed, looks like there is another problem, but does not crash anymore.

```
curl https://sh.rustup.rs -sSf | sh
info: downloading installer

Welcome to Rust!

This will download and install the official compiler for the Rust programming
language, and its package manager, Cargo.

It will add the cargo, rustc, rustup and other commands to Cargo's bin
directory, located at:

  /home/lu_zero/.cargo/bin

This path will then be added to your PATH environment variable by modifying the
profile file located at:

  /home/lu_zero/.profile

You can uninstall at any time with rustup self uninstall and these changes will
be reverted.

WARNING: This is beta software.

Current installation options:

   default host triple: powerpc64le-unknown-linux-gnu
     default toolchain: stable
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
1

info: syncing channel updates for 'stable-powerpc64le-unknown-linux-gnu'
error: target not found: 'powerpc64le-unknown-linux-gnu'
rustup: command failed: /tmp/tmp.QE0JSGRSLn/rustup-init
```
